version: 2.1
jobs:
  build:
    docker:
      - image: circleci/openjdk:17-buster-node
    environment:
      - BROWSERSTACK_USERNAME: ${browserstack_username}
      - BROWSERSTACK_ACCESS_KEY: ${browserstack_access_key}
    steps:
      - checkout
      - run:
          name: Run Appium Tests
          command: |
            chmod +x gradlew
            ./gradlew clean test -Plogin_test

workflows:
  version: 2
  build-test:
    jobs:
      - build