name: Run Tests from Docker Image (BrowserStack)

on:
  workflow_dispatch:
  push:
    branches: [ "main" ]

jobs:
  run-tests:
    runs-on: ubuntu-latest

    env:
      BROWSERSTACK_USERNAME: ${{ secrets.BROWSERSTACK_USERNAME }}
      BROWSERSTACK_ACCESS_KEY: ${{ secrets.BROWSERSTACK_ACCESS_KEY }}
      BROWSERSTACK_ANDROID_APP: ${{ secrets.BROWSERSTACK_ANDROID_APP }}

      DOCKERHUB_USERNAME: landowolf
      IMAGE_NAME: appium-tests

    steps:
      - name: Pull Docker image
        run: |
          docker pull $DOCKERHUB_USERNAME/$IMAGE_NAME:latest

      - name: Run tests inside container
        run: |
          docker run --rm \
            -e TEST_SUITE=testng-browserstack \
            -e RUN_ON_BROWSERSTACK=true \
            -e BROWSERSTACK_USERNAME=$BROWSERSTACK_USERNAME \
            -e BROWSERSTACK_ACCESS_KEY=$BROWSERSTACK_ACCESS_KEY \
            -e BROWSERSTACK_ANDROID_APP=$BROWSERSTACK_ANDROID_APP \
            $DOCKERHUB_USERNAME/$IMAGE_NAME:latest